### ISSUE TITLE
Add rel=canonical

### ISSUE THREAD

**Issue by janoszen** [mauricesvay/FullHackerNews#10]
Your service displays full articles that are overwhelmingly subject to copyright in their entirety. This may, in and of its own, constitute copyright infringement.

To lessen the effects and indeed act as a reputable aggregator, I would strongly recommend adding the rel=canonical tag to the HTML output so as to not appear in search engine results.

**Comment by mauricesvay** [comment]
Good idea.

**Comment by mauricesvay** [comment]
Looks like a page can only have one `<link rel="canonical">`, so it can't be used. I'll use a `robots.txt` file instead.
