### ISSUE TITLE
Add documentation about loading algorithm

### ISSUE THREAD

**Issue by ad-si** [mauricesvay/FullHackerNews#14]
Cool project, thanks for building it! :grin:

Can you maybe document somewhere how exactly the reloading of the hosted fullhn.com site works.
When are articles added / removed from the list?

**Comment by mauricesvay** [comment]
Hey @ad-si ,

articles are refreshed every time cron.php is executed. 
In the case of fullhn.com, a cron task refreshes articles every 15 minutes.
Every 15 minutes, all articles are replaced by articles found in this feed: `http://news.ycombinator.com/rss`.

Hope that helps.

**Comment by ad-si** [comment]
Ok, thanks, good to know.
Unfortunately that means the hosted version is not particularly suited to generate a digest once a day.
But I guess the code could be easily modified accordingly, right?

**Comment by mauricesvay** [comment]
Running the cron task every day instead of every 15 minutes would probably work. The caveat is that you would get the top articles at this exact moment, not the top articles of the day.
