### ISSUE TITLE
Force reload on page view

### ISSUE THREAD

**Issue by rosoposo** [mauricesvay/FullHackerNews#8]
Is it possible to have say fullhn.com?reload=true and this will clear the cache and reload automatically. This will help me set bookmark and access latest content when users have internet connection.

**Comment by mauricesvay** [comment]
@rosoposo I'm not sure what you mean. Do you want the page to reload automatically when new articles are downloaded?

**Comment by rosoposo** [comment]
Thanks for getting back. 
If I open https://www.fullhn.com it says "New articles available" on top in orange. I would like a direct link like https://www.fullhn.com?reload=true and when visited will automatically download the latest and clear cache. 

This way I can bookmark the URL and have latest content with one click. So just a manual direct link with parameter in URL to force update articles.

**Comment by mauricesvay** [comment]
Just in case, clicking on "New articles available" reloads the page with the new content.
I can generate a page with only the latest articles, but it wouldn't work offline. Would that solve your problem?

**Comment by webdigi** [comment]
Generating a new page with only the latest articles will work. It was better to have direct link which would work like the user clicked on "New articles available" and update the cache.

however, yes. It is still better to have a page with latest articles even if wont work offline.

**Comment by mauricesvay** [comment]
I'll see what I can do. The site currently HTML5 AppCache. The site is always loaded from cache for speed and offline support. Once it's loaded, it checks if there are new articles. When new articles are available, you are invited to reload the page to view them.
In this architecture, it's hard to clear the cache, that's why I'm offering to build a page that would never be cached.

**Comment by davidfrothin** [comment]
Understood. New page sounds fine.

**Comment by mauricesvay** [comment]
There's a new https://www.fullhn.com/latest.html that shouldn't use the cache. Let me know if that works for you.

**Comment by davidfrothin** [comment]
Awesome. Works well.

**Comment by mauricesvay** [comment]
Fixed by 83ad9140e038407202668fcb84bd249e4a94c426

**Comment by rosoposo** [comment]
Did anything change with this? It looks like the reload bar shows instead of directly loading articles now. Latest.html behaves like the main site now.
